// Default STT keyterm seed: common D&D spell/monster names that tables say in
// English mid-Hebrew. Seeding these into Soniox's context makes it transcribe
// them in exact Latin spelling (instead of Hebraizing), so they match the SRD.
//
// The provider caps context terms (~100) and the store prioritizes pinned terms,
// so this is an ordered "greatest hits" list (most-spoken first). It's validated
// against the loaded compendium at runtime, so any non-SRD entry here is simply
// dropped — edit freely.

export const DEFAULT_KEYTERM_CANDIDATES: string[] = [
  // --- High-frequency combat / utility spells ---
  'Fireball',
  'Magic Missile',
  'Counterspell',
  'Eldritch Blast',
  'Fire Bolt',
  'Cure Wounds',
  'Healing Word',
  'Shield',
  'Bless',
  'Bane',
  'Guiding Bolt',
  'Sacred Flame',
  'Vicious Mockery',
  'Hex',
  "Hunter's Mark",
  'Hold Person',
  'Misty Step',
  'Scorching Ray',
  'Spiritual Weapon',
  'Spirit Guardians',
  'Lightning Bolt',
  'Dispel Magic',
  'Haste',
  'Slow',
  'Fly',
  'Sleep',
  'Web',
  'Thunderwave',
  'Burning Hands',
  'Charm Person',
  'Faerie Fire',
  'Command',
  'Suggestion',
  'Invisibility',
  'Greater Invisibility',
  'Polymorph',
  'Banishment',
  'Dimension Door',
  'Wall of Fire',
  'Cone of Cold',
  'Hypnotic Pattern',
  'Revivify',
  'Mass Healing Word',
  'Guidance',
  'Mage Hand',
  'Minor Illusion',
  'Prestidigitation',
  'Ray of Frost',
  'Detect Magic',
  'Mage Armor',
  'Disintegrate',
  'Chain Lightning',
  'Finger of Death',
  'Teleport',
  'Meteor Swarm',
  'Power Word Kill',
  'Wish',
  // --- Common monsters ---
  'Goblin',
  'Hobgoblin',
  'Bugbear',
  'Kobold',
  'Orc',
  'Gnoll',
  'Skeleton',
  'Zombie',
  'Ghoul',
  'Wight',
  'Wraith',
  'Specter',
  'Bandit',
  'Cultist',
  'Acolyte',
  'Guard',
  'Veteran',
  'Knight',
  'Mage',
  'Priest',
  'Assassin',
  'Berserker',
  'Wolf',
  'Dire Wolf',
  'Brown Bear',
  'Giant Spider',
  'Owlbear',
  'Ogre',
  'Troll',
  'Hill Giant',
  'Ettin',
  'Harpy',
  'Basilisk',
  'Cockatrice',
  'Gelatinous Cube',
  'Mimic',
  'Animated Armor',
  'Rust Monster',
  'Bulette',
  'Will-o\'-Wisp',
  'Gargoyle',
  'Werewolf',
  'Wererat',
  'Vampire',
  'Lich',
  'Imp',
  'Quasit',
  'Succubus',
  'Treant',
  'Dryad',
]
